define({
  "Agent Carr":                  { enabled: true,  faction: "Vydar"   },
  "Airborne Elite":              { enabled: true,  faction: "Jandar"  },
  "Alastair MacDirk":            { enabled: true,  faction: "Jandar"  },
  "Anubian Wolves":              { enabled: true,  faction: "Utgar"   },
  "Aphotia":                     { enabled: true,  faction: "Choobar" },
  "Arkmer":                      { enabled: true,  faction: "Ullar"   },
  "Ariella":                     { enabled: false, faction: "Ullar"   },
  "Arrow Gruts":                 { enabled: true,  faction: "Utgar"   },
  "Aubrien Archers":             { enabled: true,  faction: "Ullar"   },
  "Basilisk":                    { enabled: false, faction: "Choobar" },
  "Belthasar":                   { enabled: true,  faction: "Choobar" },
  "Blade Gruts":                 { enabled: true,  faction: "Utgar"   },
  "Blastatrons":                 { enabled: true,  faction: "Vydar"   },
  "Braxas":                      { enabled: true,  faction: "Vydar"   },
  "Brunak":                      { enabled: true,  faction: "Utgar"   },
  "Chardris":                    { enabled: true,  faction: "Ullar"   },
  "Charon":                      { enabled: false, faction: "Jacob"   },
  "Charos":                      { enabled: true,  faction: "Ullar"   },
  "Concan":                      { enabled: true,  faction: "Jandar"  },
  "Crixus":                      { enabled: true,  faction: "Einar"   },
  "Crucian":                     { enabled: true,  faction: "Choobar" },
  "Deadeye Dan":                 { enabled: true,  faction: "Ullar"   },
  "Deadwood":                    { enabled: true,  faction: "Choobar" },
  "Deathstalkers":               { enabled: true,  faction: "Utgar"   },
  "Deathwalker 7000":            { enabled: true,  faction: "Utgar"   },
  "Deathwalker 8000":            { enabled: true,  faction: "Utgar"   },
  "Deathwalker 9000":            { enabled: true,  faction: "Utgar"   },
  "Dumutef Guard":               { enabled: true,  faction: "Utgar"   },
  "Dund":                        { enabled: true,  faction: "Vydar"   },
  "Elemental Golems":            { enabled: true,  faction: "Vydar"   },
  "Elite Onyx Vipers":           { enabled: true,  faction: "Ullar"   },
  "Emirroon":                    { enabled: true,  faction: "Ullar"   },
  "Fenril":                      { enabled: false, faction: "Jacob"   },
  "Festus":                      { enabled: true,  faction: "Jacob"   },
  "Finn":                        { enabled: true,  faction: "Jandar"  },
  "Firefly":                     { enabled: true,  faction: "Ullar"   },
  "Frank Farmer":                { enabled: false, faction: "Vydar"   },
  "Galf":                        { enabled: false, faction: "Choobar" },
  "Gladiatrons":                 { enabled: true,  faction: "Vydar"   },
  "Gorillinators":               { enabled: true,  faction: "Vydar"   },
  "Grimnak":                     { enabled: true,  faction: "Utgar"   },
  "Grok Riders":                 { enabled: true,  faction: "Utgar"   },
  "Guilty McCreech":             { enabled: true,  faction: "Einar"   },
  "Izumi Samurai":               { enabled: true,  faction: "Einar"   },
  "James Murphy":                { enabled: true,  faction: "Vydar"   },
  "Johnny 'Shotgun' Sullivan":   { enabled: true,  faction: "Jandar"  },
  "Jotun":                       { enabled: true,  faction: "Ullar"   },
  "Kato Katsuro":                { enabled: true,  faction: "Einar"   },
  "Kelda":                       { enabled: true,  faction: "Jandar"  },
  "Kenku Sneak":                 { enabled: true,  faction: "Choobar" },
  "Khosumet":                    { enabled: true,  faction: "Utgar"   },
  "Knights of Weston":           { enabled: true,  faction: "Jandar"  },
  "Kozuke Samurai":              { enabled: true,  faction: "Einar"   },
  "Krav Maga Agents":            { enabled: true,  faction: "Vydar"   },
  "Krug":                        { enabled: true,  faction: "Utgar"   },
  "Lilith":                      { enabled: true,  faction: "Choobar" },
  "MacDirk Warriors":            { enabled: true,  faction: "Jandar"  },
  "Maggotbrain Zombies":         { enabled: false, faction: "Utgar"   },
  "Major Q10":                   { enabled: true,  faction: "Vydar"   },
  "Major Q9":                    { enabled: true,  faction: "Vydar"   },
  "Major X17":                   { enabled: true,  faction: "Vydar"   },
  "Marcus Decimus":              { enabled: true,  faction: "Einar"   },
  "Marrden Hounds":              { enabled: true,  faction: "Utgar"   },
  "Marrden Nagrubs":             { enabled: true,  faction: "Utgar"   },
  "Marro Drones":                { enabled: true,  faction: "Utgar"   },
  "Marro Drudge":                { enabled: true,  faction: "Utgar"   },
  "Marro Hive":                  { enabled: false, faction: "Utgar"   },
  "Marro Stingers":              { enabled: true,  faction: "Utgar"   },
  "Marro Warriors":              { enabled: true,  faction: "Utgar"   },
  "Me-Burq-Sa":                  { enabled: true,  faction: "Utgar"   },
  "Microcorp Agents":            { enabled: true,  faction: "Vydar"   },
  "Mimring":                     { enabled: true,  faction: "Utgar"   },
  "Minions of Utgar":            { enabled: true,  faction: "Utgar"   },
  "Minutemen":                   { enabled: true,  faction: "Jandar"  },
  "Moriko":                      { enabled: true,  faction: "Ullar"   },
  "Morsbane":                    { enabled: true,  faction: "Ullar"   },
  "Nakita Agents":               { enabled: true,  faction: "Vydar"   },
  "Nathril":                     { enabled: true,  faction: "Jacob"   },
  "Ne-Gok-Sa":                   { enabled: true,  faction: "Utgar"   },
  "Nilfheim":                    { enabled: true,  faction: "Jandar"  },
  "Ninjas of the Northern Wind": { enabled: true,  faction: "Einar"   },
  "Nixy":                        { enabled: true,  faction: "Jacob"   },
  "Obsidian Guards":             { enabled: true,  faction: "Utgar"   },
  "Omnicron Snipers":            { enabled: true,  faction: "Jandar"  },
  "Otonashi":                    { enabled: true,  faction: "Vydar"   },
  "Parmenio":                    { enabled: true,  faction: "Einar"   },
  "R-66Y":                       { enabled: true,  faction: "Ullar"   },
  "Raelin, 1st Edition":         { enabled: true,  faction: "Jandar"  },
  "Raelin, 2nd Edition":         { enabled: true,  faction: "Jandar"  },
  "Rat Bastards":                { enabled: true,  faction: "Utgar"   },
  "Red Coats":                   { enabled: true,  faction: "Einar"   },
  "Retiarius":                   { enabled: true,  faction: "Einar"   },
  "Roman Archers":               { enabled: true,  faction: "Einar"   },
  "Roman Legionnaires":          { enabled: true,  faction: "Einar"   },
  "Sacred Band":                 { enabled: true,  faction: "Einar"   },
  "Saylind":                     { enabled: true,  faction: "Ullar"   },
  "Sentinels of Jandar":         { enabled: true,  faction: "Jandar"  },
  "Sgt. Drake, 1st Edition":     { enabled: true,  faction: "Jandar"  },
  "Sgt. Drake, 2nd Edition":     { enabled: true,  faction: "Jandar"  },
  "Shaolin Ascetic":             { enabled: true,  faction: "Ullar"   },
  "Shaolin Monks":               { enabled: true,  faction: "Ullar"   },
  "Shiori":                      { enabled: true,  faction: "Einar"   },
  "Sir Denrick":                 { enabled: true,  faction: "Jandar"  },
  "Sir Dupuis":                  { enabled: true,  faction: "Jandar"  },
  "Slimeclaw":                   { enabled: true,  faction: "Vydar"   },
  "Sonic Boom":                  { enabled: false, faction: "Choobar" },
  "Sonlen":                      { enabled: true,  faction: "Ullar"   },
  "Spartacus":                   { enabled: true,  faction: "Einar"   },
  "Su-Bak-Na":                   { enabled: true,  faction: "Utgar"   },
  "Sudema":                      { enabled: true,  faction: "Vydar"   },
  "Swog Rider":                  { enabled: true,  faction: "Utgar"   },
  "Syvarris":                    { enabled: true,  faction: "Ullar"   },
  "Taelord":                     { enabled: true,  faction: "Utgar"   },
  "Tagawa Samurai":              { enabled: true,  faction: "Einar"   },
  "Tarn Viking Warriors":        { enabled: true,  faction: "Jandar"  },
  "Tarsus":                      { enabled: true,  faction: "Ullar"   },
  "Templar Cavalry":             { enabled: false, faction: "Jandar"  },
  "Theracus":                    { enabled: true,  faction: "Ullar"   },
  "Thorgrim":                    { enabled: true,  faction: "Jandar"  },
  "Tor-Kul-Na":                  { enabled: false, faction: "Utgar"   },
  "Tornak":                      { enabled: true,  faction: "Utgar"   },
  "Ulginesh":                    { enabled: true,  faction: "Ullar"   },
  "Valguard":                    { enabled: true,  faction: "Einar"   },
  "Venoc Devourers":             { enabled: true,  faction: "Ullar"   },
  "Venoc Vipers":                { enabled: true,  faction: "Ullar"   },
  "Venoc Warlord":               { enabled: true,  faction: "Ullar"   },
  "Venomancer":                  { enabled: true,  faction: "Ullar"   },
  "Veshnir":                     { enabled: true,  faction: "Ullar"   },
  "Warriors of Ashra":           { enabled: true,  faction: "Ullar"   },
  "Wolves of Badru":             { enabled: true,  faction: "Utgar"   },
  "Zettian Guards":              { enabled: true,  faction: "Utgar"   }
})
