CardNames = [
  "Agent Carr",
  "Airborne Elite",
  "Alastair Macdirk",
  "Anubian Wolves",
  "Aphotia",
  "Arkmer",
  "Arrow Gruts",
  "Aubrien Archers",
  "Basilisk",
  "Blade Gruts",
  "Blastatrons",
  "Braxas",
  "Brunak",
  "Chardris",
  "Charos",
  "Concan",
  "Crixus",
  "Crucian",
  "Deadeye Dan",
  "Deadwood",
  "Deathstalkers",
  "Deathwalker 7000",
  "Deathwalker 8000",
  "Deathwalker 9000",
  "Dumutef Guard",
  "Dund",
  "Elemental Golems",
  "Elite Onyx Vipers",
  "Emirroon",
  "Festus",
  "Finn",
  "Firefly",
  "Gladiatrons",
  "Gorillinators",
  "Grimnak",
  "Grok Riders",
  "Guilty McCreech",
  "Izumi Samurai",
  "James Murphy",
  "Johnny 'Shotgun' Sullivan",
  "Jotun",
  "Kato Katsuro",
  "Kelda",
  "Kenku Sneak",
  "Khosumet",
  "Knights of Weeston",
  "Kozuke Samurai",
  "Krav Maga Agents",
  "Krug",
  "MacDirk Warriors",
  "Major Q10",
  "Major Q9",
  "Major X17",
  "Marcus Decimus",
  "Marrden Hounds",
  "Marrden Nagrubs",
  "Marro Drones",
  "Marro Drudge",
  "Marro Hive",
  "Marro Stingers",
  "Marro Warriors",
  "Me-Burq-Sa",
  "Microcorp Agents",
  "Mimring",
  "Minions of Utgar",
  "Minutemen",
  "Moriko",
  "Morsbane",
  "Nakita Agents",
  "Ne-Gok-Sa",
  "Nilfheim",
  "Ninjas of the Northern Wind",
  "Obsidian Guards",
  "Omnicron Snipers",
  "Otonashi",
  "Parmenio",
  "Raelin, 1st Edition",
  "Raelin, 2nd Edition",
  "Rat Bastards",
  "Red Coats",
  "Retiarius",
  "Roman Archers",
  "Roman Legionnaires",
  "Sacred Band",
  "Saylind",
  "Sentinels of Jandar",
  "Sgt. Drake, 1st Edition",
  "Sgt. Drake, 2nd Edition",
  "Shaolin Monks",
  "Shiori",
  "Sir Denrick",
  "Sir Dupuis",
  "Sonic Boom",
  "Sonlen",
  "Spartacus",
  "Su-Bak-Na",
  "Sudema",
  "Swog Rider",
  "Syvarris",
  "Taelord",
  "Tagawa Samurai",
  "Tarn Viking Warriors",
  "Templar Cavalry",
  "Theracus",
  "Thorgrim",
  "Tor-Kul-Na",
  "Tornak",
  "Ulginesh",
  "Valguard",
  "Venoc Devourers",
  "Venoc Vipers",
  "Venoc Warlord",
  "Veshnir",
  "Warriors of Ashra",
  "Wolves of Badru",
  "Zettian Guards"
]

exports.CardNames = CardNames
