Cards = {
  "Agent Carr": { enabled: true },
  "Airborne Elite": { enabled: true },
  "Alastair Macdirk": { enabled: true },
  "Anubian Wolves": { enabled: true },
  "Aphotia": { enabled: true },
  "Arkmer": { enabled: true },
  "Arrow Gruts": { enabled: true },
  "Aubrien Archers": { enabled: true },
  "Basilisk": { enabled: true },
  "Blade Gruts": { enabled: true },
  "Blastatrons": { enabled: true },
  "Braxas": { enabled: true },
  "Brunak": { enabled: true },
  "Chardris": { enabled: true },
  "Charos": { enabled: true },
  "Concan": { enabled: true },
  "Crixus": { enabled: true },
  "Crucian": { enabled: true },
  "Deadeye Dan": { enabled: true },
  "Deadwood": { enabled: true },
  "Deathstalkers": { enabled: true },
  "Deathwalker 7000": { enabled: true },
  "Deathwalker 8000": { enabled: true },
  "Deathwalker 9000": { enabled: true },
  "Dumutef Guard": { enabled: true },
  "Dund": { enabled: true },
  "Elemental Golems": { enabled: true },
  "Elite Onyx Vipers": { enabled: true },
  "Emirroon": { enabled: true },
  "Festus": { enabled: true },
  "Finn": { enabled: true },
  "Firefly": { enabled: true },
  "Gladiatrons": { enabled: true },
  "Gorillinators": { enabled: true },
  "Grimnak": { enabled: true },
  "Grok Riders": { enabled: true },
  "Guilty McCreech": { enabled: true },
  "Izumi Samurai": { enabled: true },
  "James Murphy": { enabled: true },
  "Johnny 'Shotgun' Sullivan": { enabled: true },
  "Jotun": { enabled: true },
  "Kato Katsuro": { enabled: true },
  "Kelda": { enabled: true },
  "Kenku Sneak": { enabled: true },
  "Khosumet": { enabled: true },
  "Knights of Weeston": { enabled: true },
  "Kozuke Samurai": { enabled: true },
  "Krav Maga Agents": { enabled: true },
  "Krug": { enabled: true },
  "MacDirk Warriors": { enabled: true },
  "Major Q10": { enabled: true },
  "Major Q9": { enabled: true },
  "Major X17": { enabled: true },
  "Marcus Decimus": { enabled: true },
  "Marrden Hounds": { enabled: true },
  "Marrden Nagrubs": { enabled: true },
  "Marro Drones": { enabled: true },
  "Marro Drudge": { enabled: true },
  "Marro Hive": { enabled: true },
  "Marro Stingers": { enabled: true },
  "Marro Warriors": { enabled: true },
  "Me-Burq-Sa": { enabled: true },
  "Microcorp Agents": { enabled: true },
  "Mimring": { enabled: true },
  "Minions of Utgar": { enabled: true },
  "Minutemen": { enabled: true },
  "Moriko": { enabled: true },
  "Morsbane": { enabled: true },
  "Nakita Agents": { enabled: true },
  "Ne-Gok-Sa": { enabled: true },
  "Nilfheim": { enabled: true },
  "Ninjas of the Northern Wind": { enabled: true },
  "Obsidian Guards": { enabled: true },
  "Omnicron Snipers": { enabled: true },
  "Otonashi": { enabled: true },
  "Parmenio": { enabled: true },
  "Raelin, 1st Edition": { enabled: true },
  "Raelin, 2nd Edition": { enabled: true },
  "Rat Bastards": { enabled: true },
  "Red Coats": { enabled: true },
  "Retiarius": { enabled: true },
  "Roman Archers": { enabled: true },
  "Roman Legionnaires": { enabled: true },
  "Sacred Band": { enabled: true },
  "Saylind": { enabled: true },
  "Sentinels of Jandar": { enabled: true },
  "Sgt. Drake, 1st Edition": { enabled: true },
  "Sgt. Drake, 2nd Edition": { enabled: true },
  "Shaolin Monks": { enabled: true },
  "Shiori": { enabled: true },
  "Sir Denrick": { enabled: true },
  "Sir Dupuis": { enabled: true },
  "Sonic Boom": { enabled: true },
  "Sonlen": { enabled: true },
  "Spartacus": { enabled: true },
  "Su-Bak-Na": { enabled: true },
  "Sudema": { enabled: true },
  "Swog Rider": { enabled: true },
  "Syvarris": { enabled: true },
  "Taelord": { enabled: true },
  "Tagawa Samurai": { enabled: true },
  "Tarn Viking Warriors": { enabled: true },
  "Templar Cavalry": { enabled: true },
  "Theracus": { enabled: true },
  "Thorgrim": { enabled: true },
  "Tor-Kul-Na": { enabled: true },
  "Tornak": { enabled: true },
  "Ulginesh": { enabled: true },
  "Valguard": { enabled: true },
  "Venoc Devourers": { enabled: true },
  "Venoc Vipers": { enabled: true },
  "Venoc Warlord": { enabled: true },
  "Veshnir": { enabled: true },
  "Warriors of Ashra": { enabled: true },
  "Wolves of Badru": { enabled: true },
  "Zettian Guards": { enabled: true }
}

exports.Cards = Cards
